/** Vietnamese text for backend-provided settings enum labels and descriptions. */
export const VI_SCHEMA_OPTION_TEXT: Readonly<Record<string, string>> = {
	Stable: "Bản ổn định",
	Canary: "Bản xem trước (Canary)",
	Mechanical: "Phát hiện theo quy tắc",
	"Short (5m)": "Ngắn hạn (5 phút)",
	"Long (1h)": "Dài hạn (1 giờ)",
	"Provider default — Anthropic uses 5m entries kept warm by idle keep-alive refreshes; PI_CACHE_RETENTION still applies":
		"Sử dụng mặc định của nhà cung cấp; Anthropic sử dụng mục lưu đệm 5 phút được làm ấm định kỳ khi rảnh; PI_CACHE_RETENTION vẫn được áp dụng.",
	"Cheapest cache writes; Anthropic keeps the entry warm with bounded keep-alive refreshes while idle":
		"Chi phí ghi cache thấp nhất; Anthropic giữ ấm mục lưu đệm bằng các lần làm mới giới hạn khi rảnh.",
	"1h TTL where the provider supports it; pricier writes, no keep-alive refresh requests":
		"TTL 1 giờ khi nhà cung cấp hỗ trợ; chi phí ghi cao hơn, không gửi yêu cầu làm mới giữ ấm.",
	"Disable prompt caching and cache-affinity routing":
		"Tắt bộ nhớ đệm prompt và định tuyến theo tính tương đồng cache.",
	Off: "Tắt",
	"Do not prevent any sleep": "Không ngăn chặn chế độ ngủ",
	"Prevent Idle Sleep": "Ngăn chế độ ngủ khi rảnh",
	"Keep the system awake while a session is open (caffeinate -i)":
		"Giữ hệ thống luôn thức khi phiên đang mở (caffeinate -i)",
	"Prevent Display Sleep": "Ngăn màn hình ngủ",
	"Also keep the display from idle-sleeping (caffeinate -i -d)":
		"Đồng thời ngăn màn hình ngủ khi rảnh (caffeinate -i -d)",
	"Prevent System Sleep": "Ngăn hệ thống ngủ",
	"Also block all system sleep on AC and declare the user active (caffeinate -i -d -s -u)":
		"Đồng thời chặn mọi chế độ ngủ của hệ thống khi dùng nguồn AC và khai báo người dùng đang hoạt động (caffeinate -i -d -s -u)",
	off: "Tắt",
	"0 turns": "0 lượt",
	"Allow every concern/blocker to interrupt.": "Cho phép mọi mối lo ngại/trở ngại gây gián đoạn.",
	"1 turn": "1 lượt",
	"2 turns": "2 lượt",
	"3 turns": "3 lượt",
	"Default.": "Mặc định.",
	"4 turns": "4 lượt",
	"5 turns": "5 lượt",
	Global: "Toàn cục",
	"Save role models in the active profile config (current behavior)":
		"Lưu mô hình vai trò trong cấu hình hồ sơ đang hoạt động (hành vi hiện tại)",
	"Per-project": "Theo từng dự án",
	"Save project role models in .omp/config.yml; missing project roles use global defaults":
		"Lưu mô hình vai trò của dự án trong .omp/config.yml; các vai trò dự án còn thiếu sẽ dùng mặc định toàn cục",
	Unicode: "Unicode",
	"Standard symbols (default)": "Ký hiệu chuẩn (mặc định)",
	"Nerd Font": "Nerd Font",
	"Requires Nerd Font": "Yêu cầu Nerd Font",
	ASCII: "ASCII",
	"Maximum compatibility": "Tương thích tối đa",
	Default: "Mặc định",
	"Model, path, git, context, tokens, cost": "Mô hình, đường dẫn, git, ngữ cảnh, token, chi phí",
	Minimal: "Tối giản",
	"Path and git only": "Chỉ đường dẫn và git",
	Compact: "Gọn gàng",
	"Model, git, cost, context": "Mô hình, git, chi phí, ngữ cảnh",
	Full: "Đầy đủ",
	"All segments including time": "Mọi phân đoạn bao gồm thời gian",
	Nerd: "Nerd",
	"Maximum info with Nerd Font icons": "Thông tin tối đa với biểu tượng Nerd Font",
	"No special characters": "Không có ký tự đặc biệt",
	Custom: "Tùy chỉnh",
	"User-defined segments": "Các phân đoạn do người dùng định nghĩa",
	Powerline: "Powerline",
	"Solid arrows (Nerd Font)": "Mũi tên đặc (Nerd Font)",
	"Thin chevron": "Dấu góc nhọn mảnh",
	"Thin arrows (Nerd Font)": "Mũi tên mảnh (Nerd Font)",
	Slash: "Gạch chéo",
	"Forward slashes": "Dấu gạch chéo xuôi",
	Pipe: "Gạch đứng",
	"Vertical pipes": "Dấu gạch đứng",
	Block: "Khối",
	"Solid blocks": "Khối đặc",
	None: "Không có",
	"Space only": "Chỉ khoảng trắng",
	"Greater-than signs": "Dấu lớn hơn",
	"1 KB": "1 KB",
	"~250 tokens": "Khoảng 250 token",
	"2.5 KB": "2.5 KB",
	"~625 tokens": "Khoảng 625 token",
	"5 KB": "5 KB",
	"~1.25K tokens": "Khoảng 1.25K token",
	"10 KB": "10 KB",
	"~2.5K tokens": "Khoảng 2.5K token",
	"20 KB": "20 KB",
	"~5K tokens": "Khoảng 5K token",
	"30 KB": "30 KB",
	"~7.5K tokens": "Khoảng 7.5K token",
	"50 KB": "50 KB",
	"Default; ~12.5K tokens": "Mặc định; khoảng 12.5K token",
	"75 KB": "75 KB",
	"~19K tokens": "Khoảng 19K token",
	"100 KB": "100 KB",
	"~25K tokens": "Khoảng 25K token",
	"200 KB": "200 KB",
	"~50K tokens": "Khoảng 50K token",
	"500 KB": "500 KB",
	"~125K tokens": "Khoảng 125K token",
	"1 MB": "1 MB",
	"~250K tokens": "Khoảng 250K token",
	"Default; ~5K tokens": "Mặc định; khoảng 5K token",
	"~12.5K tokens": "Khoảng 12.5K token",
	"0 KB": "0 KB",
	"Disabled; tail-only truncation": "Đã tắt; chỉ cắt bớt phần đuôi",
	"No per-line cap": "Không có giới hạn trên mỗi dòng",
	Tight: "Chặt chẽ",
	Loose: "Rộng rãi",
	"50 lines": "50 dòng",
	"100 lines": "100 dòng",
	"~500 tokens": "Khoảng 500 token",
	"250 lines": "250 dòng",
	"500 lines": "500 dòng",
	"Default; ~2.5K tokens": "Mặc định; khoảng 2.5K token",
	"1000 lines": "1000 dòng",
	"2000 lines": "2000 dòng",
	"~10K tokens": "Khoảng 10K token",
	"5000 lines": "5000 dòng",
	auto: "Tự động",
	always: "Luôn luôn",
	Classic: "Cổ điển",
	"Soft cosine wave sweeping across the text": "Sóng cosine nhẹ nhàng quét qua văn bản",
	"KITT Scanner": "Máy quét KITT",
	"Knight Rider 1982 red light bouncing left-right": "Ánh đèn đỏ Knight Rider 1982 di chuyển qua lại trái phải",
	Disabled: "Đã tắt",
	"No animation; static muted text": "Không hoạt ảnh; văn bản tĩnh làm mờ",
	"Auto-detect per prompt": "Tự động phát hiện theo từng prompt",
	min: "Tối thiểu",
	"Very brief reasoning (~1k tokens)": "Suy luận rất ngắn gọn (~1k token)",
	low: "Thấp",
	"Light reasoning (~2k tokens)": "Suy luận nhẹ (~2k token)",
	medium: "Trung bình",
	"Moderate reasoning (~8k tokens)": "Suy luận vừa phải (~8k token)",
	high: "Cao",
	"Deep reasoning (~16k tokens)": "Suy luận sâu (~16k token)",
	xhigh: "Rất cao",
	"Extended reasoning (~32k tokens)": "Suy luận mở rộng (~32k token)",
	max: "Tối đa",
	"Maximum reasoning the model supports": "Mức suy luận tối đa mà mô hình hỗ trợ",
	Auto: "Tự động",
	"Inline descriptors for Gemini models; keep them in tool schemas otherwise":
		"Nội dòng mô tả cho mô hình Gemini; các trường hợp khác giữ nguyên trong schema công cụ",
	On: "Bật",
	"Always inline descriptors in the system prompt": "Luôn nội dòng mô tả trong prompt hệ thống",
	"Keep descriptors in provider tool schemas only": "Chỉ giữ mô tả trong schema công cụ của nhà cung cấp",
	"Terse, evidence-first engineer; dense, action-oriented replies":
		"Kỹ sư súc tích, ưu tiên chứng cứ; phản hồi cô đọng, hướng đến hành động",
	Friendly: "Thân thiện",
	"Warm, encouraging collaborator focused on momentum and morale":
		"Cộng tác viên ấm áp, khích lệ, tập trung vào tiến độ và tinh thần làm việc",
	Pragmatic: "Thực dụng",
	"Direct, efficient engineer focused on clarity and rigor":
		"Kỹ sư thẳng thắn, hiệu quả, tập trung vào sự rõ ràng và chặt chẽ",
	"Omit the personality block entirely": "Bỏ qua hoàn toàn phần tính cách",
	"Use provider default": "Sử dụng mặc định của nhà cung cấp",
	Deterministic: "Xác định",
	Focused: "Tập trung",
	Balanced: "Cân bằng",
	Creative: "Sáng tạo",
	"Maximum variety": "Đa dạng tối đa",
	"Very focused": "Rất tập trung",
	Broad: "Mở rộng",
	"No nucleus filtering": "Không lọc nucleus (top-p)",
	"Greedy top token": "Chọn token xác suất cao nhất (greedy)",
	"Very permissive": "Rất thoải mái",
	Strict: "Nghiêm ngặt",
	"No penalty": "Không phạt",
	"Mild novelty": "Khuyến khích mới lạ nhẹ",
	"Encourage novelty": "Khuyến khích mới lạ",
	"Strong novelty": "Khuyến khích mới lạ mạnh",
	"Allow repetition": "Cho phép lặp lại",
	"Mild penalty": "Phạt nhẹ",
	"Strong penalty": "Phạt nặng",
	Low: "Thấp",
	"Prefer concise responses": "Ưu tiên phản hồi ngắn gọn",
	Medium: "Trung bình",
	"Balance brevity and detail (default)": "Cân bằng giữa ngắn gọn và chi tiết (mặc định)",
	High: "Cao",
	"Prefer detailed responses": "Ưu tiên phản hồi chi tiết",
	"Omit service_tier (standard processing)": "Bỏ qua service_tier (xử lý tiêu chuẩn)",
	"Provider default tier selection": "Lựa chọn gói mặc định của nhà cung cấp",
	"Standard priority processing": "Xử lý ưu tiên tiêu chuẩn",
	Flex: "Flex",
	"Lower cost, higher latency when available": "Chi phí thấp hơn, độ trễ cao hơn khi khả dụng",
	Scale: "Scale",
	"Scale Tier credits when available": "Tín dụng gói Scale khi khả dụng",
	Priority: "Ưu tiên",
	"Faster, higher cost (premium request)": "Nhanh hơn, chi phí cao hơn (yêu cầu cao cấp)",
	"Standard processing": "Xử lý tiêu chuẩn",
	'Fast mode (`speed: "fast"`) on supported direct Claude models; ignored on Bedrock/Vertex':
		'Chế độ nhanh (`speed: "fast"`) trên các mô hình Claude trực tiếp được hỗ trợ; bỏ qua trên Bedrock/Vertex',
	"Lower cost, higher latency (Gemini API + Vertex)": "Chi phí thấp hơn, độ trễ cao hơn (Gemini API + Vertex)",
	"Faster, higher reliability (Gemini API + Vertex)": "Nhanh hơn, độ tin cậy cao hơn (Gemini API + Vertex)",
	Inherit: "Kế thừa",
	"Match the main agent's live per-family tiers": "Khớp với gói cấp đang chạy của agent chính theo từng dòng mô hình",
	"Provider default tier selection (OpenAI family)": "Lựa chọn gói mặc định của nhà cung cấp (dòng OpenAI)",
	"Standard priority processing (OpenAI family)": "Xử lý ưu tiên tiêu chuẩn (dòng OpenAI)",
	"Flexible capacity tier (OpenAI/Google families)": "Gói dung lượng linh hoạt (dòng OpenAI/Google)",
	"Scale Tier credits (OpenAI family)": "Tín dụng gói Scale (dòng OpenAI)",
	"Priority on every supported family of the spawned model": "Ưu tiên trên mọi dòng được hỗ trợ của mô hình được tạo",
	"1 retry": "Thử lại 1 lần",
	"2 retries": "Thử lại 2 lần",
	"3 retries": "Thử lại 3 lần",
	"5 retries": "Thử lại 5 lần",
	"10 retries": "Thử lại 10 lần",
	"Act only when nearly exhausted": "Chỉ hành động khi gần cạn kiệt",
	"Balanced safety margin": "Mức dự phòng an toàn cân bằng",
	Conservative: "Thận trọng",
	"Early protection": "Bảo vệ sớm",
	"Very conservative": "Rất thận trọng",
	"Confirm interactively": "Xác nhận tương tác",
	"Keep interactive sessions on the primary until confirmed; background agents auto-fallback":
		"Giữ phiên tương tác ở mô hình chính cho đến khi xác nhận; agent nền tự động chuyển dự phòng",
	"Auto-fallback": "Tự động chuyển dự phòng",
	"Always select the next eligible configured fallback": "Luôn chọn mô hình dự phòng kế tiếp đủ điều kiện đã cấu hình",
	"Fail closed": "Thất bại đóng (Fail-closed)",
	"Do not spend reserve quota or select a fallback": "Không sử dụng hạn ngạch dự trữ hoặc chọn mô hình dự phòng",
	"Cooldown expiry": "Hết thời gian hạ nhiệt",
	"Return to the primary model after its suppression window ends":
		"Quay lại mô hình chính sau khi khoảng thời gian tạm dừng kết thúc",
	Never: "Không bao giờ",
	"Stay on the fallback model until manually changed": "Giữ ở mô hình dự phòng cho đến khi thay đổi thủ công",
	all: "tất cả",
	"one-at-a-time": "từng cái một",
	immediate: "ngay lập tức",
	wait: "chờ",
	Prompt: "Prompt",
	"Re-submit the prompt as a follow-up message (current behavior)":
		"Gửi lại prompt dưới dạng tin nhắn tiếp theo (hành vi hiện tại)",
	"Compact the session context, then re-submit the prompt": "Nén ngữ cảnh phiên, sau đó gửi lại prompt",
	Reset: "Đặt lại",
	"Start a new session, then re-submit the prompt": "Bắt đầu phiên mới, sau đó gửi lại prompt",
	branch: "nhánh",
	tree: "cây",
	none: "không",
	default: "mặc định",
	"no-tools": "không có công cụ",
	"user-only": "chỉ người dùng",
	"labeled-only": "chỉ có nhãn",
	"3 items": "3 mục",
	"5 items": "5 mục",
	"7 items": "7 mục",
	"10 items": "10 mục",
	"15 items": "15 mục",
	"20 items": "20 mục",
	"Don't check for plugin updates": "Không kiểm tra cập nhật plugin",
	Notify: "Thông báo",
	"Check on startup and notify when updates are available": "Kiểm tra khi khởi động và thông báo khi có bản cập nhật",
	"Check on startup and auto-install updates": "Kiểm tra khi khởi động và tự động cài đặt bản cập nhật",
	Summary: "Tóm tắt",
	"Show release and change counts with a /changelog hint":
		"Hiển thị số lượng phát hành và thay đổi cùng gợi ý /changelog",
	Expanded: "Mở rộng",
	"Show the recent release notes in full": "Hiển thị đầy đủ ghi chú phát hành gần đây",
	Hidden: "Ẩn",
	"Do not show release notes on startup": "Không hiển thị ghi chú phát hành khi khởi động",
	on: "bật",
	"15 seconds": "15 giây",
	"30 seconds": "30 giây",
	"60 seconds": "60 giây",
	"120 seconds": "120 giây",
	"1 minute": "1 phút",
	"2 minutes": "2 phút",
	"4 minutes": "4 phút",
	"5 minutes": "5 phút",
	"10 minutes": "10 phút",
	"Encrypted Blob": "Blob mã hóa",
	"Upload to the share server (no GitHub account needed; avoids gist API rate limits)":
		"Tải lên máy chủ chia sẻ (không cần tài khoản GitHub; tránh giới hạn tốc độ API gist)",
	"GitHub Gist": "GitHub Gist",
	"Push to a secret gist (needs authenticated gh), falling back to the share server":
		"Đẩy lên gist bí mật (cần gh đã xác thực), chuyển sang máy chủ chia sẻ nếu thất bại",
	"Fast (Whisper base)": "Nhanh (Whisper base)",
	"Whisper base, multilingual. Smallest + fastest; lowest accuracy. Best for low-resource machines.":
		"Whisper base, đa ngôn ngữ. Nhỏ nhất + nhanh nhất; độ chính xác thấp nhất. Tốt nhất cho máy cấu hình yếu.",
	"Balanced (Whisper small)": "Cân bằng (Whisper small)",
	"Whisper small, multilingual. More accurate than Fast, still light on CPU/RAM.":
		"Whisper small, đa ngôn ngữ. Chính xác hơn Nhanh, vẫn nhẹ với CPU/RAM.",
	"Turbo (Whisper large-v3)": "Turbo (Whisper large-v3)",
	"Whisper large-v3-turbo, 99 languages. Widest language coverage; large download, slower.":
		"Whisper large-v3-turbo, 99 ngôn ngữ. Độ phủ ngôn ngữ rộng nhất; tải về dung lượng lớn, chậm hơn.",
	"Parakeet TDT v3 (SoTA)": "Parakeet TDT v3 (SoTA)",
	"NVIDIA Parakeet TDT 0.6B v3, 25 languages. Open ASR Leaderboard leader — best accuracy and far fastest decoding. Default.":
		"NVIDIA Parakeet TDT 0.6B v3, 25 ngôn ngữ. Đứng đầu bảng xếp hạng Open ASR — độ chính xác cao nhất và giải mã nhanh vượt trội. Mặc định.",
	"Never automatically submit; insert dictation and remain in editor.":
		"Không bao giờ tự động gửi; chèn nội dung đọc chính tả và giữ nguyên trong trình chỉnh sửa.",
	Release: "Khi thả phím",
	"Submit on release if the utterance has 2+ words to avoid accidental sends.":
		"Gửi khi thả phím nếu lời nói có từ 2 từ trở lên để tránh gửi nhầm.",
	"Release with complete sentence": "Thả phím khi hoàn thành câu",
	"Submit on release if the utterance ends with sentence-terminal punctuation (. ? ! etc.).":
		"Gửi khi thả phím nếu câu nói kết thúc bằng dấu chấm câu (. ? ! v.v.).",
	"When I Say Submit": "Khi tôi nói Submit",
	"Submit if the utterance ends with a word containing 'submit' (strips that word before submitting).":
		"Gửi nếu câu nói kết thúc bằng từ chứa 'submit' (xóa từ đó trước khi gửi).",
	"Context-full": "Đầy ngữ cảnh",
	"Summarize in-place and keep the current session": "Tóm tắt tại chỗ và giữ lại phiên hiện tại",
	Handoff: "Bàn giao",
	"Generate handoff and continue in a new session": "Tạo bản bàn giao và tiếp tục trong phiên mới",
	Shake: "Tinh giản",
	"Drop heavy content (tool results + large blocks) in place; recover via artifact":
		"Bỏ bớt nội dung nặng (kết quả công cụ + khối lớn) tại chỗ; khôi phục qua artifact",
	Snapcompact: "Snapcompact",
	"Archive history onto dense bitmap images the model reads back; no LLM call":
		"Lưu trữ lịch sử thành hình ảnh bitmap mật độ cao để mô hình đọc lại; không gọi LLM",
	"OpenAI server compaction": "Nén phía máy chủ OpenAI",
	"Use provider-native OpenAI-compatible server compaction when the active route supports it":
		"Sử dụng tính năng nén phía máy chủ tương thích OpenAI của nhà cung cấp khi tuyến đường hiện tại hỗ trợ",
	"Archive history onto dense bitmap images the active vision model reads back; no LLM call":
		"Lưu trữ lịch sử thành hình ảnh bitmap mật độ cao mà mô hình thị giác đang dùng đọc lại; không gọi LLM",
	"Generate a handoff document and continue from it as the compaction summary":
		"Tạo tài liệu bàn giao và tiếp tục từ tài liệu đó làm bản tóm tắt nén",
	"Soft compaction": "Nén mềm",
	"Summarize in place with a compaction model without using server compaction":
		"Tóm tắt tại chỗ bằng mô hình nén mà không dùng tính năng nén phía máy chủ",
	"Drop recoverable heavy content in place without an LLM call":
		"Bỏ bớt nội dung nặng có thể khôi phục tại chỗ mà không gọi LLM",
	"Disable automatic context maintenance (same behavior as Auto-compact off)":
		"Tắt tự động duy trì ngữ cảnh (hành vi tương tự như tắt Tự động nén)",
	"Legacy reserve-based threshold": "Ngưỡng dựa trên lượng dự trữ cũ",
	"Extremely early maintenance": "Duy trì cực kỳ sớm",
	"Very early maintenance": "Duy trì rất sớm",
	"Early maintenance": "Duy trì sớm",
	"Moderately early maintenance": "Duy trì tương đối sớm",
	"Halfway point": "Điểm giữa",
	"Moderate context usage": "Sử dụng ngữ cảnh vừa phải",
	"Slightly aggressive": "Hơi quyết liệt",
	"Typical threshold": "Ngưỡng thông thường",
	"Aggressive context usage": "Sử dụng ngữ cảnh quyết liệt",
	"Very aggressive": "Rất quyết liệt",
	"Near context limit": "Gần giới hạn ngữ cảnh",
	"Use percentage-based threshold": "Sử dụng ngưỡng dựa trên phần trăm",
	"25K tokens": "25K token",
	"Quarter of a 200K window": "Một phần tư cửa sổ 200K",
	"50K tokens": "50K token",
	"Half of a 200K window": "Một nửa cửa sổ 200K",
	"100K tokens": "100K token",
	"150K tokens": "150K token",
	"Three-quarters of a 200K window": "Ba phần tư cửa sổ 200K",
	"200K tokens": "200K token",
	"Full standard context window": "Toàn bộ cửa sổ ngữ cảnh tiêu chuẩn",
	"300K tokens": "300K token",
	"Large context window": "Cửa sổ ngữ cảnh lớn",
	"500K tokens": "500K token",
	"Very large context window": "Cửa sổ ngữ cảnh rất lớn",
	"400K tokens": "400K token",
	"600K tokens": "600K token",
	"700K tokens": "700K token",
	"800K tokens": "800K token",
	"900K tokens": "900K token",
	"30 minutes": "30 phút",
	"1 hour": "1 giờ",
	"Keep the system prompt as text.": "Giữ prompt hệ thống dưới dạng văn bản.",
	"AGENTS.md": "AGENTS.md",
	"Only move loaded context-file instructions to images, when that saves tokens.":
		"Chỉ chuyển chỉ dẫn tệp ngữ cảnh đã tải thành hình ảnh khi giúp tiết kiệm token.",
	All: "Tất cả",
	"Move the full system prompt to images, when that saves tokens.":
		"Chuyển toàn bộ prompt hệ thống thành hình ảnh khi giúp tiết kiệm token.",
	"Use native tool calls unless the model is known not to support them.":
		"Sử dụng gọi công cụ gốc trừ khi mô hình được biết là không hỗ trợ.",
	Native: "Gốc (Native)",
	"Use provider-native tool calls.": "Sử dụng gọi công cụ gốc của nhà cung cấp.",
	GLM: "GLM",
	"Use GLM-style in-band tool calls.": "Sử dụng gọi công cụ trong luồng kiểu GLM.",
	Hermes: "Hermes",
	"Use Hermes-style in-band tool calls.": "Sử dụng gọi công cụ trong luồng kiểu Hermes.",
	Kimi: "Kimi",
	"Use Kimi-style in-band tool calls.": "Sử dụng gọi công cụ trong luồng kiểu Kimi.",
	XML: "XML",
	"Use generic XML in-band tool calls.": "Sử dụng gọi công cụ trong luồng kiểu XML chung.",
	Anthropic: "Anthropic",
	"Use Anthropic-style in-band tool calls.": "Sử dụng gọi công cụ trong luồng kiểu Anthropic.",
	DeepSeek: "DeepSeek",
	"Use DeepSeek-style in-band tool calls.": "Sử dụng gọi công cụ trong luồng kiểu DeepSeek.",
	Harmony: "Harmony",
	"Use Harmony-style in-band tool calls.": "Sử dụng gọi công cụ trong luồng kiểu Harmony.",
	Qwen3: "Qwen3",
	"Use the Qwen3 owned dialect.": "Sử dụng phương ngữ riêng của Qwen3.",
	Gemini: "Gemini",
	"Use the Gemini owned dialect.": "Sử dụng phương ngữ riêng của Gemini.",
	Gemma: "Gemma",
	"Use the Gemma owned dialect.": "Sử dụng phương ngữ riêng của Gemma.",
	MiniMax: "MiniMax",
	"Use the MiniMax owned dialect.": "Sử dụng phương ngữ riêng của MiniMax.",
	"Picks a shape tuned for the current model, falling back to its provider family.":
		"Chọn hình dạng được tinh chỉnh cho mô hình hiện tại, chuyển về dòng nhà cung cấp nếu cần.",
	"8x8 repeated, black": "8x8 lặp lại, đen",
	"unscii square cell, black ink, every line printed twice with the copy on a pale highlight band.":
		"Ô vuông unscii, mực đen, mỗi dòng in hai lần với bản sao trên dải tô sáng nhạt.",
	"8x8 repeated, sentence hues": "8x8 lặp lại, sắc thái câu",
	"Repeated grid with ink cycling six hues at sentence boundaries.":
		"Lưới lặp lại với mực xoay vòng sáu sắc thái tại ranh giới câu.",
	"8x8, black": "8x8, đen",
	"Plain unscii square cell, single-printed lines, black ink.":
		"Ô vuông unscii thông thường, các dòng in đơn, mực đen.",
	"8x8, sentence hues": "8x8, sắc thái câu",
	"Plain unscii square cell with sentence-hue ink.": "Ô vuông unscii thông thường với mực theo sắc thái câu.",
	"6x6 dense, black": "6x6 dày đặc, đen",
	"unscii squeezed to 6x6 — densest readable cell, fewest frames — in black ink.":
		"unscii nén xuống 6x6 — ô đọc được dày đặc nhất, ít khung nhất — bằng mực đen.",
	"6x6 dense, sentence hues": "6x6 dày đặc, sắc thái câu",
	"Densest cell with sentence-hue ink.": "Ô dày đặc nhất với mực theo sắc thái câu.",
	"5x8 legacy, black": "5x8 cũ, đen",
	"Original X.org 5x8 glyphs on the 2576px frame, black ink.":
		"Ký tự X.org 5x8 nguyên bản trên khung 2576px, mực đen.",
	"5x8 legacy, sentence hues": "5x8 cũ, sắc thái câu",
	"The original snapcompact shape (pre-shape-table sessions rendered this).":
		"Hình dạng snapcompact nguyên bản (các phiên trước bảng hình dạng hiển thị kiểu này).",
	"6x12, dimmed stopwords": "6x12, làm mờ stopword",
	"X.org 6x12 glyphs, black ink, function words dimmed gray.":
		"Ký tự X.org 6x12, mực đen, các từ chức năng làm mờ màu xám.",
	"8x13, black": "8x13, đen",
	"X.org 8x13 glyphs, black ink.": "Ký tự X.org 8x13, mực đen.",
	"8x13 on 16px pitch, black": "8x13 khoảng cách 16px, đen",
	"8x13 glyphs on an 8x16 cell (extra leading), black ink.": "Ký tự 8x13 trên ô 8x16 (thêm giãn dòng), mực đen.",
	"8x13 on 22px pitch (leading), black": "8x13 khoảng cách 22px (giãn dòng), đen",
	"8x13 glyphs on an 8x22 cell — extra line spacing so rows don't crowd. Default for OpenAI/Google.":
		"Ký tự 8x13 trên ô 8x22 — thêm khoảng cách dòng để các hàng không bị chật. Mặc định cho OpenAI/Google.",
	"8x13 on 11px advance (tracking), black": "8x13 bước tiến 11px (khoảng cách chữ), đen",
	"8x13 glyphs on an 11x16 cell — extra letter spacing so characters don't merge. Default for Anthropic.":
		"Ký tự 8x13 trên ô 11x16 — thêm khoảng cách chữ để các ký tự không bị dính. Mặc định cho Anthropic.",
	"Silver 16, CJK": "Silver 16, CJK",
	"Embedded Silver TrueType font on a 16px grid for CJK and other non-Latin text.":
		"Phông chữ Silver TrueType nhúng trên lưới 16px cho văn bản CJK và phi Latin khác.",
	"Doc 8on16, black": "Doc 8on16, đen",
	"Two word-wrapped newspaper columns of 8x13 glyphs on a 16px pitch, black ink.":
		"Hai cột báo tự động xuống dòng gồm các ký tự 8x13 trên khoảng cách 16px, mực đen.",
	"Doc 8on16, sentence hues": "Doc 8on16, sắc thái câu",
	"Two-column doc layout with sentence-hue ink.": "Bố cục tài liệu hai cột với mực theo sắc thái câu.",
	"Doc 8on16, sentence hues + dimmed stopwords": "Doc 8on16, sắc thái câu + làm mờ stopword",
	"Two-column doc layout, sentence-hue ink, function words dimmed gray.":
		"Bố cục tài liệu hai cột, mực theo sắc thái câu, từ chức năng làm mờ màu xám.",
	"No memory subsystem runs": "Không chạy phân hệ bộ nhớ",
	Local: "Cục bộ",
	"Local rollout summarisation pipeline (memory_summary.md)":
		"Quy trình tóm tắt triển khai cục bộ (memory_summary.md)",
	Hindsight: "Hindsight",
	"Vectorize Hindsight remote memory service": "Dịch vụ bộ nhớ từ xa Vectorize Hindsight",
	Mnemopi: "Mnemopi",
	"Local SQLite recall/retain backend with optional embeddings":
		"Backend lưu giữ/truy xuất SQLite cục bộ với embedding tùy chọn",
	Sharpshooter: "Sharpshooter",
	"Friction-gated project decision files (architecture/product/style), consolidated in the background":
		"Tệp quyết định dự án dựa trên tín hiệu xung đột (kiến trúc/sản phẩm/phong cách), được hợp nhất ở chế độ nền",
	"One shared Mnemopi bank for every project": "Một ngân hàng Mnemopi dùng chung cho mọi dự án",
	"Per project": "Theo từng dự án",
	"Project-local Mnemopi bank per cwd basename": "Ngân hàng Mnemopi cục bộ theo tên thư mục làm việc (cwd)",
	"Per project (tagged)": "Theo từng dự án (có gắn thẻ)",
	"Write to a project-local bank but merge project + shared recall results":
		"Ghi vào ngân hàng cục bộ của dự án nhưng hợp nhất kết quả truy xuất dự án + dùng chung",
	"English (bge-base-en-v1.5)": "Tiếng Anh (bge-base-en-v1.5)",
	"BAAI/bge-base-en-v1.5 (768d), English-only": "BAAI/bge-base-en-v1.5 (768d), chỉ tiếng Anh",
	"Multilingual (multilingual-e5-large)": "Đa ngôn ngữ (multilingual-e5-large)",
	"intfloat/multilingual-e5-large (1024d), cross-language recall":
		"intfloat/multilingual-e5-large (1024d), truy xuất xuyên ngôn ngữ",
	"Disable Mnemopi LLM-backed extraction": "Tắt trích xuất hỗ trợ bởi LLM của Mnemopi",
	"Online (tiny)": "Trực tuyến (tiny)",
	"Use the online tiny model (the TINY role from /models, else @smol)":
		"Sử dụng mô hình tiny trực tuyến (vai trò TINY từ /models, nếu không thì @smol)",
	Remote: "Từ xa",
	"Use the Mnemopi remote LLM settings below": "Sử dụng các cài đặt LLM từ xa của Mnemopi bên dưới",
	"One shared bank — every project sees the same memories":
		"Một ngân hàng dùng chung — mọi dự án đều thấy cùng các bộ nhớ",
	"Isolated bank per cwd basename — projects cannot see each other's memories":
		"Ngân hàng biệt lập theo tên thư mục làm việc — các dự án không thể thấy bộ nhớ của nhau",
	"Shared bank, retains tagged with project:<cwd>. Recall surfaces project + untagged global memories together":
		"Ngân hàng dùng chung, lưu giữ được gắn thẻ project:<cwd>. Truy xuất hiển thị cả bộ nhớ dự án + bộ nhớ toàn cục chưa gắn thẻ",
	"Full session": "Toàn bộ phiên",
	"Upsert one document per session (recommended)":
		"Cập nhật hoặc chèn (upsert) một tài liệu cho mỗi phiên (khuyến nghị)",
	"Last turn": "Lượt trước",
	"Chunked retention sliced by turn boundaries": "Lưu giữ phân đoạn cắt theo ranh giới lượt trao đổi",
	mid: "giữa chừng",
	discard: "loại bỏ",
	keep: "giữ lại",
	"Interrupt on prose and tool streams": "Ngắt cả luồng văn bản và luồng công cụ",
	"prose-only": "chỉ văn bản",
	"Interrupt only on reply/thinking matches": "Chỉ ngắt khi phản hồi/suy nghĩ khớp",
	"tool-only": "chỉ công cụ",
	"Interrupt only on tool-call argument matches": "Chỉ ngắt khi đối số gọi công cụ khớp",
	never: "không bao giờ",
	"Never interrupt; inject warning after completion": "Không bao giờ ngắt; chèn cảnh báo sau khi hoàn thành",
	once: "một lần",
	"after-gap": "sau khoảng trống",
	"5 messages": "5 tin nhắn",
	"10 messages": "10 tin nhắn",
	"15 messages": "15 tin nhắn",
	"20 messages": "20 tin nhắn",
	"30 messages": "30 tin nhắn",
	apply_patch: "apply_patch",
	hashline: "hashline",
	patch: "patch",
	replace: "replace",
	Lenient: "Khoan dung",
	Moderate: "Vừa phải",
	"200 lines": "200 dòng",
	"300 lines": "300 dòng",
	aggressive: "quyết liệt",
	session: "phiên",
	"per-call": "mỗi lần gọi",
	"Always ask": "Luôn hỏi",
	"Auto-approve read-only tools; require confirmation for write and exec tools.":
		"Tự động phê duyệt công cụ chỉ đọc; yêu cầu xác nhận cho công cụ ghi và thực thi.",
	Write: "Ghi",
	"Auto-approve read-only and write tools; require confirmation for exec tools such as bash, eval, browser, and task.":
		"Tự động phê duyệt công cụ chỉ đọc và ghi; yêu cầu xác nhận cho các công cụ thực thi như bash, eval, browser và task.",
	Yolo: "Yolo",
	"Auto-approve read, write, and exec tools. User policy can still require confirmation or block calls.":
		"Tự động phê duyệt các công cụ đọc, ghi và thực thi. Chính sách người dùng vẫn có thể yêu cầu xác nhận hoặc chặn lệnh gọi.",
	"1 reminder": "1 lần nhắc",
	"2 reminders": "2 lần nhắc",
	"3 reminders": "3 lần nhắc",
	"5 reminders": "5 lần nhắc",
	"Model decides; no automatic todo list": "Mô hình quyết định; không tự động tạo danh sách việc cần làm",
	Preferred: "Ưu tiên",
	"Suggests a todo list on the first message (reminder, not forced)":
		"Gợi ý danh sách việc cần làm ở tin nhắn đầu tiên (chỉ nhắc nhở, không ép buộc)",
	Always: "Luôn luôn",
	"Forces a comprehensive todo list on the first message":
		"Bắt buộc tạo danh sách việc cần làm toàn diện ở tin nhắn đầu tiên",
	"0 lines": "0 dòng",
	"1 line": "1 dòng",
	"2 lines": "2 dòng",
	"3 lines": "3 dòng",
	"5 lines": "5 dòng",
	"10 lines": "10 dòng",
	"Auto (only for models without vision)": "Tự động (chỉ dành cho mô hình không có thị giác)",
	"3 minutes": "3 phút",
	"No limit": "Không giới hạn",
	"5 seconds": "5 giây",
	"10 seconds": "10 giây",
	Smart: "Thông minh",
	"Default — adaptive 5s→5m, resets when you stop polling": "Mặc định — thích ứng 5s→5m, đặt lại khi bạn dừng thăm dò",
	"All Devices": "Tất cả thiết bị",
	"Inline docs and schemas for every mounted device.": "Tài liệu và schema nội dòng cho mọi thiết bị được gắn kết.",
	"Built-ins Only": "Chỉ phần tích hợp sẵn",
	"Inline built-in docs; fetch MCP and extension docs on demand.":
		"Tài liệu tích hợp sẵn nội dòng; tìm nạp tài liệu MCP và tiện ích mở rộng theo yêu cầu.",
	"Catalog Only": "Chỉ danh mục",
	"List every device; fetch all docs on demand.": "Liệt kê mọi thiết bị; tìm nạp tất cả tài liệu theo yêu cầu.",
	"No isolation": "Không cách ly",
	"Let the PAL pick the best available backend": "Để PAL chọn backend khả dụng tốt nhất",
	APFS: "APFS",
	"macOS clonefile reflink (APFS)": "macOS clonefile reflink (APFS)",
	btrfs: "btrfs",
	"btrfs subvolume snapshot": "Ảnh chụp nhanh subvolume btrfs",
	ZFS: "ZFS",
	"ZFS snapshot + clone": "Ảnh chụp nhanh + nhân bản ZFS",
	Reflink: "Reflink",
	"Linux FICLONE per-file reflink": "Linux FICLONE reflink từng tệp",
	Overlayfs: "Overlayfs",
	"Linux kernel overlay (or fuse-overlayfs fallback)": "Lớp phủ nhân Linux (hoặc dự phòng fuse-overlayfs)",
	ProjFS: "ProjFS",
	"Windows Projected File System": "Hệ thống tệp dự chiếu Windows (ProjFS)",
	"Block clone": "Nhân bản khối (Block clone)",
	"Windows FSCTL_DUPLICATE_EXTENTS_TO_FILE (NTFS/ReFS)": "Windows FSCTL_DUPLICATE_EXTENTS_TO_FILE (NTFS/ReFS)",
	"Recursive copy": "Sao chép đệ quy",
	"git worktree if available, otherwise recursive copy": "git worktree nếu khả dụng, nếu không thì sao chép đệ quy",
	Patch: "Patch",
	"Combine diffs and git apply": "Kết hợp các diff và git apply",
	Branch: "Nhánh (Branch)",
	"Commit per task, merge with --no-ff": "Commit theo từng tác vụ, hợp nhất với --no-ff",
	Generic: "Chung chung",
	"Static commit message": "Thông điệp commit tĩnh",
	AI: "AI",
	"AI-generated commit message from diff": "Thông điệp commit do AI tạo từ diff",
	"Model decides when to delegate": "Mô hình quyết định khi nào ủy quyền",
	"Adds delegation guidance to the system prompt": "Thêm hướng dẫn ủy quyền vào prompt hệ thống",
	"Prompt guidance plus a first-turn delegation reminder":
		"Hướng dẫn trong prompt kèm lời nhắc ủy quyền ở lượt đầu tiên",
	Unlimited: "Không giới hạn",
	"1 task": "1 tác vụ",
	"2 tasks": "2 tác vụ",
	"4 tasks": "4 tác vụ",
	"8 tasks": "8 tác vụ",
	"16 tasks": "16 tác vụ",
	"32 tasks": "32 tác vụ",
	"64 tasks": "64 tác vụ",
	Single: "Đơn",
	Double: "Đôi",
	Triple: "Ba",
	"15 minutes": "15 phút",
	"90 requests": "90 yêu cầu",
	"150 requests": "150 yêu cầu",
	"200 requests": "200 yêu cầu",
	Instant: "Tức thì",
	Perplexity: "Perplexity",
	"Uses auth when configured; explicit selection falls back to anonymous search":
		"Sử dụng xác thực khi đã cấu hình; lựa chọn rõ ràng sẽ dự phòng về tìm kiếm ẩn danh",
	"Google Search grounding via Gemini (uses google-gemini-cli or google-antigravity OAuth)":
		"Cơ sở tìm kiếm Google Search qua Gemini (dùng google-gemini-cli hoặc google-antigravity OAuth)",
	"Claude's native web_search tool (uses Anthropic OAuth or ANTHROPIC_API_KEY)":
		"Công cụ web_search gốc của Claude (dùng Anthropic OAuth hoặc ANTHROPIC_API_KEY)",
	OpenAI: "OpenAI",
	"OpenAI's native web_search (uses ChatGPT OAuth via /login openai-codex)":
		"web_search gốc của OpenAI (dùng ChatGPT OAuth qua /login openai-codex)",
	xAI: "xAI",
	"Grok web search via xAI Responses API (uses SuperGrok/X Premium+ OAuth via /login xai-oauth, or XAI_API_KEY)":
		"Tìm kiếm web Grok qua xAI Responses API (dùng SuperGrok/X Premium+ OAuth qua /login xai-oauth, hoặc XAI_API_KEY)",
	"Z.AI": "Z.AI",
	"Calls Z.AI webSearchPrime MCP": "Gọi MCP webSearchPrime của Z.AI",
	Exa: "Exa",
	"API via /login exa or EXA_API_KEY; explicit keyless fallback via MCP":
		"API qua /login exa hoặc EXA_API_KEY; dự phòng không cần khóa rõ ràng qua MCP",
	TinyFish: "TinyFish",
	"Requires TINYFISH_API_KEY": "Yêu cầu TINYFISH_API_KEY",
	Jina: "Jina",
	"Requires JINA_API_KEY": "Yêu cầu JINA_API_KEY",
	Kagi: "Kagi",
	"Requires KAGI_API_KEY and Kagi Search API beta access":
		"Yêu cầu KAGI_API_KEY và quyền truy cập thử nghiệm Kagi Search API",
	Tavily: "Tavily",
	"Requires TAVILY_API_KEY": "Yêu cầu TAVILY_API_KEY",
	Firecrawl: "Firecrawl",
	"Uses Firecrawl API when FIRECRAWL_API_KEY is set; falls back to keyless mode":
		"Sử dụng Firecrawl API khi FIRECRAWL_API_KEY được đặt; dự phòng về chế độ không khóa",
	Brave: "Brave",
	"Requires BRAVE_API_KEY": "Yêu cầu BRAVE_API_KEY",
	"Kimi Code search (requires a Kimi Code Console key via KIMI_SEARCH_API_KEY/MOONSHOT_SEARCH_API_KEY or /login kimi-code; not MOONSHOT_API_KEY)":
		"Tìm kiếm Kimi Code (yêu cầu khóa Kimi Code Console qua KIMI_SEARCH_API_KEY/MOONSHOT_SEARCH_API_KEY hoặc /login kimi-code; không phải MOONSHOT_API_KEY)",
	Parallel: "Parallel",
	"Requires PARALLEL_API_KEY": "Yêu cầu PARALLEL_API_KEY",
	Synthetic: "Synthetic",
	"Requires SYNTHETIC_API_KEY": "Yêu cầu SYNTHETIC_API_KEY",
	SearXNG: "SearXNG",
	"Requires SEARXNG_ENDPOINT or searxng.endpoint": "Yêu cầu SEARXNG_ENDPOINT hoặc searxng.endpoint",
	Startpage: "Startpage",
	"Credential-free scrape of Startpage (Google-backed) results; may be bot-challenged":
		"Thu thập kết quả Startpage (hỗ trợ bởi Google) không cần thông tin đăng nhập; có thể gặp xác minh bot",
	DuckDuckGo: "DuckDuckGo",
	"Credential-free best-effort fallback; may be bot-challenged on datacenter/shared-egress IPs":
		"Phương án dự phòng nỗ lực tối đa không cần thông tin đăng nhập; có thể gặp xác minh bot trên IP trung tâm dữ liệu/cổng ra dùng chung",
	Ecosia: "Ecosia",
	"Credential-free browser-backed scrape of Ecosia (Google-backed) results":
		"Thu thập kết quả Ecosia (hỗ trợ bởi Google) qua trình duyệt không cần thông tin đăng nhập",
	Google: "Google",
	"Credential-free browser-backed fallback; slower and may be bot-challenged":
		"Phương án dự phòng qua trình duyệt không cần thông tin đăng nhập; chậm hơn và có thể gặp xác minh bot",
	Mojeek: "Mojeek",
	"Credential-free browser-backed scrape of Mojeek's independent index":
		"Thu thập chỉ mục độc lập của Mojeek qua trình duyệt không cần thông tin đăng nhập",
	"Public Web": "Web công cộng",
	"Queries every credential-free engine in parallel and consolidates deduplicated results":
		"Truy vấn song song tất cả các công cụ không cần thông tin đăng nhập và hợp nhất các kết quả đã loại bỏ trùng lặp",
	"Try production endpoint, fail over to sandbox on 5xx/429":
		"Thử endpoint sản xuất, chuyển vùng dự phòng sang sandbox khi gặp lỗi 5xx/429",
	"Production Only": "Chỉ sản xuất",
	"Force production endpoint only": "Bắt buộc chỉ dùng endpoint sản xuất",
	"Sandbox Only": "Chỉ sandbox",
	"Force sandbox endpoint only": "Bắt buộc chỉ dùng endpoint sandbox",
	"OPENAI_API_KEY (gpt-image-2) or active GPT model; falls back to a connected Codex subscription":
		"OPENAI_API_KEY (gpt-image-2) hoặc mô hình GPT đang hoạt động; dự phòng về gói thuê bao Codex đã kết nối",
	"OpenAI Codex (ChatGPT)": "OpenAI Codex (ChatGPT)",
	"Uses a connected Codex / ChatGPT subscription — no OPENAI_API_KEY needed":
		"Sử dụng gói thuê bao Codex / ChatGPT đã kết nối — không cần OPENAI_API_KEY",
	Antigravity: "Antigravity",
	"Requires google-antigravity OAuth": "Yêu cầu google-antigravity OAuth",
	"xAI Grok Imagine": "xAI Grok Imagine",
	"Requires xAI Grok OAuth or XAI_API_KEY": "Yêu cầu xAI Grok OAuth hoặc XAI_API_KEY",
	"Requires GEMINI_API_KEY": "Yêu cầu GEMINI_API_KEY",
	OpenRouter: "OpenRouter",
	"Requires OPENROUTER_API_KEY": "Yêu cầu OPENROUTER_API_KEY",
	Standard: "Tiêu chuẩn",
	"Default serving path (no service_tier)": "Đường dẫn phục vụ mặc định (không có service_tier)",
	"Priority serving path: higher reliability, premium per-token pricing":
		"Đường dẫn phục vụ ưu tiên: độ tin cậy cao hơn, giá theo token cao cấp hơn",
	Arbor: "Arbor",
	Breeze: "Breeze",
	Cove: "Cove",
	Ember: "Ember",
	Juniper: "Juniper",
	Maple: "Maple",
	Sol: "Sol",
	Spruce: "Spruce",
	Vale: "Vale",
	"Prefer local on-device TTS; route .mp3 output to xAI when credentials exist":
		"Ưu tiên TTS trên thiết bị cục bộ; định tuyến đầu ra .mp3 đến xAI khi có thông tin đăng nhập",
	"On-device neural TTS (Kokoro-82M); output is WAV/PCM16":
		"TTS mạng nơ-ron trên thiết bị (Kokoro-82M); đầu ra là WAV/PCM16",
	"xAI Grok Voice": "xAI Grok Voice",
	"Requires xAI Grok OAuth or XAI_API_KEY; MP3 or WAV": "Yêu cầu xAI Grok OAuth hoặc XAI_API_KEY; MP3 hoặc WAV",
	"Kokoro-82M": "Kokoro-82M",
	"Kokoro-82M neural TTS — SoTA on-device quality, multi-voice, fully local":
		"TTS mạng nơ-ron Kokoro-82M — chất lượng hàng đầu (SoTA) trên thiết bị, đa giọng nói, hoàn toàn cục bộ",
	"Heart (American female)": "Heart (nữ Mỹ)",
	"Bella (American female)": "Bella (nữ Mỹ)",
	"Nicole (American female)": "Nicole (nữ Mỹ)",
	"Aoede (American female)": "Aoede (nữ Mỹ)",
	"Kore (American female)": "Kore (nữ Mỹ)",
	"Sarah (American female)": "Sarah (nữ Mỹ)",
	"Michael (American male)": "Michael (nam Mỹ)",
	"Fenrir (American male)": "Fenrir (nam Mỹ)",
	"Puck (American male)": "Puck (nam Mỹ)",
	"Emma (British female)": "Emma (nữ Anh)",
	"George (British male)": "George (nam Anh)",
	"Fable (British male)": "Fable (nam Anh)",
	"All (messages + thinking)": "Tất cả (tin nhắn + suy nghĩ)",
	"Assistant messages": "Tin nhắn trợ lý",
	"Final message only": "Chỉ tin nhắn cuối cùng",
	"Online (TINY role, else @smol)": "Trực tuyến (vai trò TINY, nếu không thì @smol)",
	"Online title generation: the TINY model role (set one in /models) when assigned, otherwise the online fallback (commit role, then @smol). No local download or on-device inference.":
		"Tạo tiêu đề trực tuyến: vai trò mô hình TINY (đặt trong /models) khi được gán, nếu không thì dùng phương án dự phòng trực tuyến (vai trò commit, sau đó đến @smol). Không cần tải xuống cục bộ hoặc suy luận trên thiết bị.",
	"LFM2 350M": "LFM2 350M",
	"Recommended local model; best speed/quality balance, about 212 MB cached.":
		"Mô hình cục bộ được khuyến nghị; cân bằng tốc độ/chất lượng tốt nhất, lưu đệm khoảng 212 MB.",
	"Qwen3 0.6B": "Qwen3 0.6B",
	"Most robust local option; slower first load, about 500 MB cached.":
		"Lựa chọn cục bộ mạnh mẽ nhất; tải lần đầu chậm hơn, lưu đệm khoảng 500 MB.",
	"Gemma 270M": "Gemma 270M",
	"Smallest viable local option; lower quality, lowest cache footprint.":
		"Lựa chọn cục bộ nhỏ nhất có thể dùng; chất lượng thấp hơn, chiếm dụng dung lượng lưu đệm ít nhất.",
	"Qwen2.5 0.5B": "Qwen2.5 0.5B",
	"Balanced local fallback; moderate quality and cache footprint.":
		"Phương án dự phòng cục bộ cân bằng; chất lượng và chiếm dụng dung lượng lưu đệm vừa phải.",
	"LFM2 700M": "LFM2 700M",
	"Highest-quality local option; larger and slower than LFM2 350M.":
		"Lựa chọn cục bộ chất lượng cao nhất; lớn hơn và chậm hơn LFM2 350M.",
	"CPU-only inference": "Chỉ suy luận bằng CPU",
	GPU: "GPU",
	"Accelerated provider (WebGPU/Metal, CUDA, or DirectML)": "Nhà cung cấp tăng tốc (WebGPU/Metal, CUDA hoặc DirectML)",
	CPU: "CPU",
	Metal: "Metal",
	"WebGPU alias for Apple GPUs": "Bí danh WebGPU cho GPU của Apple",
	WebGPU: "WebGPU",
	"WebGPU/Metal backend": "Backend WebGPU/Metal",
	CUDA: "CUDA",
	"NVIDIA CUDA (Linux x64)": "NVIDIA CUDA (Linux x64)",
	DirectML: "DirectML",
	"DirectML backend (Windows)": "Backend DirectML (Windows)",
	CoreML: "CoreML",
	"Apple CoreML (opt-in; can fail to load)": "Apple CoreML (tùy chọn bật; có thể không tải được)",
	"Let ONNX Runtime choose a provider": "Để ONNX Runtime tự chọn nhà cung cấp",
	WASM: "WASM",
	"WebAssembly backend": "Backend WebAssembly",
	WebNN: "WebNN",
	"WebNN backend": "Backend WebNN",
	"WebNN GPU": "WebNN GPU",
	"WebNN GPU device": "Thiết bị GPU WebNN",
	"WebNN CPU": "WebNN CPU",
	"WebNN CPU device": "Thiết bị CPU WebNN",
	"WebNN NPU": "WebNN NPU",
	"WebNN NPU device": "Thiết bị NPU WebNN",
	"Each model's shipped dtype (currently q4)": "Kiểu dữ liệu (dtype) gốc của mỗi mô hình (hiện tại là q4)",
	q4: "q4",
	"4-bit weights; smallest and fastest": "Trọng số 4-bit; nhỏ nhất và nhanh nhất",
	q4f16: "q4f16",
	"4-bit weights with fp16 activations": "Trọng số 4-bit với kích hoạt fp16",
	q8: "q8",
	"8-bit quantization": "Lượng tử hóa 8-bit",
	fp16: "fp16",
	"16-bit float; higher fidelity, larger": "Số thực 16-bit; độ trung thực cao hơn, dung lượng lớn hơn",
	fp32: "fp32",
	"Full precision; largest and slowest": "Độ chính xác đầy đủ; dung lượng lớn nhất và chậm nhất",
	int8: "int8",
	"Signed 8-bit integer": "Số nguyên có dấu 8-bit",
	uint8: "uint8",
	"Unsigned 8-bit integer": "Số nguyên không dấu 8-bit",
	bnb4: "bnb4",
	"bitsandbytes 4-bit": "bitsandbytes 4-bit",
	q2: "q2",
	"2-bit weights": "Trọng số 2-bit",
	q2f16: "q2f16",
	"2-bit weights with fp16 activations": "Trọng số 2-bit với kích hoạt fp16",
	q1: "q1",
	"1-bit weights": "Trọng số 1-bit",
	q1f16: "q1f16",
	"1-bit weights with fp16 activations": "Trọng số 1-bit với kích hoạt fp16",
	"Let transformers.js choose per device": "Để transformers.js tự chọn theo từng thiết bị",
	"Use the online model: the TINY role from /models when set, otherwise @smol. No local model download or on-device inference.":
		"Sử dụng mô hình trực tuyến: vai trò TINY từ /models khi được đặt, nếu không thì @smol. Không cần tải mô hình cục bộ hoặc suy luận trên thiết bị.",
	"Qwen3 1.7B": "Qwen3 1.7B",
	"Disabled for local inference: onnxruntime-node cannot run this ONNX export's RotaryEmbedding cache updates.":
		"Đã tắt cho suy luận cục bộ: onnxruntime-node không thể chạy các bản cập nhật cache RotaryEmbedding của bản xuất ONNX này.",
	"Llama 3.2 3B": "Llama 3.2 3B",
	"Larger Llama 3.2 option for local memory/classifier tasks; higher quality potential at higher disk/RAM/latency cost.":
		"Lựa chọn Llama 3.2 lớn hơn cho các tác vụ bộ nhớ/phân loại cục bộ; tiềm năng chất lượng cao hơn nhưng tốn đĩa/RAM/độ trễ hơn.",
	"Gemma 3 1B": "Gemma 3 1B",
	"Best consolidation/dedup; lighter footprint, but leaks small talk during extraction.":
		"Hợp nhất/khử trùng lặp tốt nhất; dung lượng nhẹ hơn, nhưng hay lọt nội dung tán ngẫu khi trích xuất.",
	"Qwen2.5 1.5B": "Qwen2.5 1.5B",
	"Best extraction granularity (atomic facts); weaker consolidation.":
		"Độ chi tiết trích xuất tốt nhất (sự kiện nguyên tử); khả năng hợp nhất yếu hơn.",
	"LFM2 1.2B": "LFM2 1.2B",
	"Fastest load; solid all-rounder, slightly noisier extraction labels.":
		"Tải nhanh nhất; toàn diện và ổn định, nhãn trích xuất hơi nhiều nhiễu.",
	"Classify prompt difficulty online with the TINY role model (set one in /models) or @smol; no local download or on-device inference.":
		"Phân loại độ khó của prompt trực tuyến bằng mô hình vai trò TINY (đặt trong /models) hoặc @smol; không cần tải về cục bộ hoặc suy luận trên thiết bị.",
	"Classifier stops at xhigh (default)": "Bộ phân loại dừng ở mức xhigh (mặc định)",
	"Classifier may resolve max where the model supports it": "Bộ phân loại có thể đưa ra mức max khi mô hình hỗ trợ",
	"Use the model's server-declared protocol": "Sử dụng giao thức máy chủ mô hình khai báo",
	"api.kimi.com": "api.kimi.com",
	"api.moonshot.ai": "api.moonshot.ai",
	"Use model/provider default websocket behavior": "Sử dụng hành vi websocket mặc định của mô hình/nhà cung cấp",
	"Disable websockets for OpenAI Codex models": "Tắt websockets cho các mô hình OpenAI Codex",
	"Force websockets for OpenAI Codex models": "Bắt buộc dùng websockets cho các mô hình OpenAI Codex",
	"Use provider defaults and PI_* timeout env vars":
		"Sử dụng mặc định của nhà cung cấp và biến môi trường thời gian chờ PI_*",
	"Disable first-event timeout": "Tắt thời gian chờ sự kiện đầu tiên",
	"Disable idle timeout": "Tắt thời gian chờ khi không hoạt động",
	"No suffix; use OpenRouter's default routing": "Không có hậu tố; sử dụng định tuyến mặc định của OpenRouter",
	":nitro": ":nitro",
	"Prioritize throughput / lowest latency": "Ưu tiên thông lượng / độ trễ thấp nhất",
	":floor": ":floor",
	"Prioritize cheapest available provider": "Ưu tiên nhà cung cấp khả dụng có giá rẻ nhất",
	":online": ":online",
	"Enable OpenRouter's web-search plugin": "Bật plugin tìm kiếm web của OpenRouter",
	":exacto": ":exacto",
	"Cherry-picked high-quality providers (only defined for select models)":
		"Các nhà cung cấp chất lượng cao được tuyển chọn kỹ (chỉ định nghĩa cho một số mô hình)",
	"Priority: native > trafilatura > lynx > parallel > jina":
		"Độ ưu tiên: native > trafilatura > lynx > parallel > jina",
	"In-process HTML→Markdown converter (always available)":
		"Bộ chuyển đổi HTML→Markdown trong tiến trình (luôn khả dụng)",
	Trafilatura: "Trafilatura",
	"Auto-installs via uv/pip": "Tự động cài đặt qua uv/pip",
	Lynx: "Lynx",
	"Requires lynx system package": "Yêu cầu gói hệ thống lynx",
	"Uses r.jina.ai reader (JINA_API_KEY optional)": "Sử dụng trình đọc r.jina.ai (JINA_API_KEY tùy chọn)",
	Unset: "Chưa đặt",
	"Check eligibility, then ask before spending the first saved reset.":
		"Kiểm tra tính hợp lệ, sau đó hỏi trước khi dùng lần đặt lại đã lưu đầu tiên.",
	Yes: "Có",
	"Spend eligible saved resets without prompting.": "Dùng các lần đặt lại đã lưu hợp lệ mà không cần hỏi.",
	No: "Không",
	"Do not run the saved-reset auto-redeem check.": "Không chạy kiểm tra tự động đổi lần đặt lại đã lưu.",
	"Enable for known prefix-cache providers (recommended)":
		"Bật cho các nhà cung cấp có bộ nhớ đệm tiền tố đã biết (khuyến nghị)",
	"Always enable append-only context": "Luôn bật ngữ cảnh chỉ thêm vào cuối (append-only)",
	"Disable append-only context": "Tắt ngữ cảnh chỉ thêm vào cuối (append-only)",
	unset: "chưa đặt",
	granted: "đã cấp quyền",
	denied: "đã từ chối",
	// ── Tùy chọn enum mới trong omp 18.2.x ──────────────────────────────────────────
	Braille: "Chữ nổi (Braille)",
	"Classic sweep (default)": "Quét cổ điển (mặc định)",
	Pulse: "Nhịp đập (Pulse)",
	"Moon filling cycle": "Chu kỳ trăng tròn",
	Dots: "Dấu chấm",
	Line: "Đường kẻ",
	Collapsed: "Thu gọn",
	"Hide the pinned jump list": "Ẩn danh sách chuyển nhanh đã ghim",
	"Show a few rows with an expander": "Hiển thị vài hàng kèm nút mở rộng",
	Percentage: "Phần trăm",
	"Solid accent line, no context feedback": "Đường kẻ nhấn liền nét, không phản hồi ngữ cảnh",
	"Used portion in accent color, remainder dimmed": "Phần đã dùng mang màu nhấn, phần còn lại làm mờ",
	Append: "Thêm vào cuối",
	"Replay the transcript at the new width below retained history":
		"Phát lại bản ghi ở độ rộng mới bên dưới lịch sử được giữ lại",
	Rebuild: "Xây dựng lại",
	"Erase all terminal scrollback, then replay one current-width transcript":
		"Xóa toàn bộ bộ đệm cuộn của terminal, sau đó phát lại một bản ghi theo độ rộng hiện tại",
	View: "Chế độ xem (chỉ đọc)",
	"Share only when /collab is run": "Chỉ chia sẻ khi chạy /collab",
	"Auto-host; the registry hands out view-only links (omp collab link --view)":
		"Tự động lưu trữ; registry sẽ phân phối liên kết chỉ xem (omp collab link --view)",
};
