/**
 * Generate the app icons from resources/icon-source.svg: a 1024px master PNG
 * (the source for the Tauri icon set) and the Linux resources/icons/*.png set.
 * Also renders the tray mark from resources/tray-source.svg into
 * src/shared/tray-mark.ts. Run: `bun run gen:icons`.
 */

import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { writeFileSync } from "node:fs";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import sharp from "sharp";

const packageRoot = path.join(import.meta.dir, "..");
const resources = path.join(packageRoot, "resources");
const svgPath = path.join(resources, "icon-source.svg");
const traySvgPath = path.join(resources, "tray-source.svg");
const trayMarkPath = path.join(packageRoot, "src", "shared", "tray-mark.ts");

/** The tray mark is 18pt drawn at 2×, so it stays crisp on HiDPI displays. */
const TRAY_MARK_SIZE = 36;
const LINUX_SIZES = [16, 32, 48, 64, 128, 256, 512, 1024];

async function render(svg: Buffer, size: number): Promise<Buffer> {
	// High density so the vector mark stays crisp when resized down.
	return sharp(svg, { density: 384 })
		.resize(size, size, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
		.png()
		.toBuffer();
}

/** One alpha byte per pixel, row-major: the tray draws its own ink per platform. */
async function renderTrayMark(svg: Buffer): Promise<Buffer> {
	const alpha = await sharp(svg, { density: 384 })
		.resize(TRAY_MARK_SIZE, TRAY_MARK_SIZE, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
		.ensureAlpha()
		.extractChannel("alpha")
		.raw()
		.toBuffer();
	if (alpha.length !== TRAY_MARK_SIZE * TRAY_MARK_SIZE) {
		throw new Error(`tray mark rendered ${alpha.length} bytes, expected ${TRAY_MARK_SIZE * TRAY_MARK_SIZE}`);
	}
	return alpha;
}

function writeTrayMark(svg: Buffer, alpha: Buffer): void {
	const sourceHash = createHash("sha256").update(svg).digest("hex");
	const source = [
		"// Generated by scripts/gen-icons.ts from resources/tray-source.svg; do not edit.",
		"",
		"/** Side of the square tray mark, in pixels (18pt at 2×). */",
		`export const TRAY_MARK_SIZE = ${TRAY_MARK_SIZE};`,
		"",
		"/** Base64 of the mark's alpha channel, one byte per pixel, row-major. */",
		`export const TRAY_MARK_ALPHA = "${alpha.toString("base64")}";`,
		"",
		"/** sha256 of resources/tray-source.svg, so a stale mark fails its test. */",
		`export const TRAY_MARK_SOURCE_SHA256 = "${sourceHash}";`,
		"",
	].join("\n");
	writeFileSync(trayMarkPath, source);
	// Biome breaks the long assignment; formatting here keeps regeneration byte-identical.
	execFileSync("bunx", ["biome", "format", "--write", trayMarkPath], { cwd: packageRoot, stdio: "inherit" });
}

async function main(): Promise<void> {
	const svg = await fs.readFile(svgPath);

	// Master 1024px PNG (the source for the Tauri icon set).
	await Bun.write(path.join(resources, "icon.png"), await render(svg, 1024));

	// Linux PNG set.
	const linuxDir = path.join(resources, "icons");
	await fs.mkdir(linuxDir, { recursive: true });
	for (const px of LINUX_SIZES) {
		await Bun.write(path.join(linuxDir, `${px}x${px}.png`), await render(svg, px));
	}

	const traySvg = await fs.readFile(traySvgPath);
	writeTrayMark(traySvg, await renderTrayMark(traySvg));

	console.log("Generated icon.png, resources/icons/*.png and src/shared/tray-mark.ts");
}

await main();
